//Получение стран
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_PENDING = 'GET_COUNTRIES_PENDING';
export const GET_COUNTRIES_FULFILLED = 'GET_COUNTRIES_FULFILLED';
export const GET_COUNTRIES_REJECTED = 'GET_COUNTRIES_REJECTED';
